title: Manifesto on Resource Reuse in Interactive Information Retrieval
#email: your-email@example.com
description: >-
  Manifesto on Resource Reuse in Interactive Information Retrieval
baseurl: ""
url: ""
github_username:  biirrr

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

header_pages:
  - manifesto/v1.0.0.md
